//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsporteNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsporteNetEntities : DbContext
    {
        public EsporteNetEntities()
            : base("name=EsporteNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CONTATO_USU> CONTATO_USU { get; set; }
        public DbSet<LOCAL_USU> LOCAL_USU { get; set; }
        public DbSet<MOVE_APOSTAS> MOVE_APOSTAS { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
