//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsporteNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVE_APOSTAS
    {
        public System.DateTime DT_ANOMES { get; set; }
        public long FK_COD_USU { get; set; }
        public long SEQUENCIA { get; set; }
        public string DSC_TIPO { get; set; }
        public long NUM_APOSTAS { get; set; }
        public Nullable<double> VLT_BRUTO { get; set; }
        public Nullable<double> VLT_PAGO { get; set; }
        public Nullable<double> VLT_COMIS { get; set; }
        public Nullable<double> VLT_LIQUID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
