//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsporteNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.MOVE_APOSTAS = new HashSet<MOVE_APOSTAS>();
        }
    
        public long COD_USU { get; set; }
        public string DSC_USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<long> COD_SUP { get; set; }
        public string DSC_NOME_USU { get; set; }
    
        public virtual CONTATO_USU CONTATO_USU { get; set; }
        public virtual CONTATO_USU CONTATO_USU1 { get; set; }
        public virtual LOCAL_USU LOCAL_USU { get; set; }
        public virtual LOCAL_USU LOCAL_USU1 { get; set; }
        public virtual ICollection<MOVE_APOSTAS> MOVE_APOSTAS { get; set; }
    }
}
